services:
  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blogapi
      POSTGRES_USER: blogapi
      POSTGRES_PASSWORD: blogapi
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  broker:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgresql-data:
    driver: local
