services:
  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: blogapi
      POSTGRES_USER: blogapi
      POSTGRES_PASSWORD: blogapi
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  broker:
    image: redis:7.2.6-alpine
  app:
    build: .
    command: ./scripts/run_django.sh
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
      - broker
    volumes:
      - ./blogapi:/opt/project/blogapi
      - ./local:/opt/project/local/
  rq:
    build: .
    command: ./scripts/run_rq.sh
    depends_on:
      - broker
      - db
    volumes:
      - ./blogapi:/opt/project/blogapi
      - ./local:/opt/project/local/
  rqscheduler:
    build: .
    command: ./scripts/run_rqscheduler.sh
    volumes:
      - ./blogapi:/opt/project/blogapi
      - ./local:/opt/project/local/
    depends_on:
      - broker
      - db
volumes:
  postgresql-data:
    driver: local
