# Generated by Django 5.1.2 on 2024-10-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authomatic_answer_delay',
            new_name='automatic_answer_delay',
        ),
    ]
