# Generated by Django 5.1.2 on 2024-10-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_is_ai_generated_comment_ai_generated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='automaticly_answer_comments',
            new_name='automatically_answer_comments',
        ),
    ]
